GET http://localhost:5000/api
###
GET http://localhost:5000/api/accounts/alex
###
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
    "title" : "alex",
    "body" : "my body"
}
###
POST http://localhost:5000/api/accounts
Content-Type: application/json

{
    "user" : "hedy",
     "currency" : "USD"
}
